### PR TITLE
Add ome.ps.as2 benchmark vs. Pegasus

### PR DESCRIPTION
**Pull request by felixhekhorn**
@igborsa is it okay if I copy your implementation of the polarized NNLO OME here?

As will be visible in the CI the benchmark fails in the last line - commenting that line out, we pass

The error will be
```
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=0
E           hg,N=2
E           Mismatched elements: 1 / 1 (100%)
E           Max absolute difference: 0.2584379
E           Max relative difference: 0.02809631
E            x: array(-9.456725+0.j)
E            y: array(-9.198287)
```

### CODE REVIEW

**Comment by igborsa** [comment]
@felixhekhorn Yes, no problem at all.

**Comment by felixhekhorn** [comment]
@igborsa as the CI shows with the last commit we are now passing the benchmark - so I think you should do the same on your side.

Just to rephrase what @giacomomagni [already said](https://github.com/NNPDF/eko/pull/368#issuecomment-2111236336) on #368 : we are using two different representation of the same object and [your fix](https://github.com/NNPDF/benchmark_pol_timelike_evol/commit/2a37eea7b45dd5c20efc53e9766a64011f94a7a7) for `ACG3` is not needed. You are using the lhs of Eq. 131 of 2211.15337, specifically Eq. 113 _as written_, which requires all objects, i.e. $g_3$ and $\beta$, to be evaluated at $N+1$ (this is what my fix is doing here and the bug you introduced changed) - we are using the rhs of Eq. 131 (and do _not_ use Eq. 113 as written), but call the linear independent $S_{-2,1}$ eventually at $N$.

In practice you just need to revert that line.

**Comment by igborsa** [comment]
Hi @felixhekhorn. 

Actually, the fix is needed. The routine ACG3(N) returns the Mellin transform already evaluated in N+1, so using ACG3(N1) would return the result evaluated in N+2 (that's what confused me when I listed the potential bugs). The correct "translation" to the eko routines is indeed

ACG3(N) = h.g_functions.mellin_g3(N1, S11)

and that's why your last modification worked.

**Comment by felixhekhorn** [comment]
> Hi @felixhekhorn.
> 
> Actually, the fix is needed. The routine ACG3(N) returns the Mellin transform already evaluated in N+1, so using ACG3(N1) would return the result evaluated in N+2 (that's what confused me when I listed the potential bugs). The correct "translation" to the eko routines is indeed
> 
> ACG3(N) = h.g_functions.mellin_g3(N1, S11)
> 
> and that's why your last modification worked.

I see ... but this means the remaining difference we have between us must come from somewhere else then $A_{hg},A_{hq},A_{gg},A_{gq}$, which would have been the prime candidates ...

**Comment by igborsa** [comment]
It seems that (at least part of) the difference we have is actually coming from the term \beta''(N+1) in A_Hg.
I was using the implementation from the code ANCONT (BET2) that apparently is not precise enough. 

Replacing BET2(N+1) -> (DPSI((N1+1)/2.d0,2) - DPSI(N1/2.d0,2))/8.d0,

where  DPSI(N,2) corresponds to the second derivative of the Digamma, seems to improve the agreement between eco and pol-pegasus

**Pull request merged**
