### PR TITLE
Drop `develop`

### PR DESCRIPTION
**Pull request by AleCandido**
In order to simplify the workflow for the newcomers, I propose to finally drop `develop` branch, together with [Git flow](https://nvie.com/posts/a-successful-git-branching-model/) altogether (i.e. stop prefixing branches with `feature/` and similar, and complex merge strategies).

In practice, not much will change:
- I might need to update some workflows (but maybe not)
- `master` won't be synced any longer with latest tag: tags are tags, and each correspond to a version, but there is no branch following them
- `master` will be the new `develop`, i.e. the main branch we are working on (as it usually is)

Feedback from people already working on this repo is appreciated.

### CODE REVIEW

**Comment by AleCandido** [comment]
All the commits here are listed by chance: we can merge them as soon as we are ready, with the old workflow, independently of this PR.

The PR will be merged only if and when we will have decided to drop `develop` branch.

**Comment by felixhekhorn** [comment]
I wonder how to enforce the idea of #163 - i.e. run benchmarks (in a first stage LHA, later even more) before releasing ... else I guess it is fine ...

**Comment by giacomomagni** [comment]
I'm happy with this. Do we plan to have a working release once this PR is merged? 

> I wonder how to enforce the idea of #163 - i.e. run benchmarks (in a first stage LHA, later even more) before releasing ... else I guess it is fine ...

That would be really great!

**Comment by AleCandido** [comment]
Just to tell also here what I already wrote to @felixhekhorn in private: I perfectly know how to do it
- use the same container of isobench
- run the benchmark runners (without firing any error in any case)
- upload the resulting db as an artifact
- (to improve) we add a function to identify pathologies, and one to compare with old db for regressions: no one will raise errors, since we have no reliable way to claim an error, but they are useful to skim the output

However, at the moment we're pretty busy with more pressing tasks, for this reason I proposed to postpone this further.
We already have a dedicated issue since some time #155

**Comment by AleCandido** [comment]
I mistakenly removed draft mode and currently unable to restore. There is no meaning behind it

**Comment by felixhekhorn** [comment]
> run benchmarks (in a first stage LHA, later even more) before releasing

here I was more worried about the formal requirement of having some sort of green tick than about the actual implementation

**Comment by AleCandido** [comment]
> here I was more worried about the formal requirement of having some sort of green tick than about the actual implementation

If you don't take care of the implementation, you will always have a green tick or always a red cross, regardless of what is happening inside.
The only part you can skip is the db upload. But if something is so broken to make benchmarks crashing, it is extremely likely it would make also unit tests or isobenchs (i.e. integration tests...) fail before, by crashing.

**Pull request merged**
