### PR TITLE
Add some pol tests

### PR DESCRIPTION
**Pull request by giacomomagni**
I think we can add this test on the polarized anomalous dimension.
(I messed up with the history because I started branching from the wrong branch)

### CODE REVIEW

**Comment by giacomomagni** [comment]
how do I access the beta function in the rust crates?

**Comment by felixhekhorn** [comment]
> how do I access the beta function in the rust crates?

eeehm, good point - it is currently not available

mmm let me think a moment ... :thinking: 

1) the easy solution is just to ignore the Rust again for the moment in this PR (and delay the problem)
2) if we want to do the proper thing, we need to find a good place on the Rust side; I'm thinking about adding yet another crate, random name suggestion: `ekoupling`, where we provide quasi the equivalent to the `eko.couplings` module: specifically, the beta functions and their solution. I'm worried about dependency management and how to disentangle stuff. Do you have an opinion? @tgiani may I ask for your opinion as well?

**Comment by giacomomagni** [comment]
> 
> 1. the easy solution is just to ignore the Rust again for the moment in this PR (and delay the problem)
> 2. if we want to do the proper thing, we need to find a good place on the Rust side; I'm thinking about adding yet another crate, random name suggestion: `ekoupling`, where we provide quasi the equivalent to the `eko.couplings` module: specifically, the beta functions and their solution. I'm worried about dependency management and how to disentangle stuff. Do you have an opinion? @tgiani may I ask for your opinion as well?

So regarding this PR, I'd postpone the problem, it's just an additional test, I can add the one unrelated to be beta function. 
For the long terms strategy I think we should provide the `ekoupling` module, but maybe you can add this to the `oxidation` road map or another issue.

**Review by felixhekhorn — APPROVED** [review]
as already said: maybe we can clean the commit history a bit (or we just keep it as is)

**Comment by felixhekhorn** [comment]
ehm, now I wonder if we should hard code beta0, i.e. sacrifice code duplication for an additional test ...

**Comment by tgiani** [comment]
> > how do I access the beta function in the rust crates?
> 
> eeehm, good point - it is currently not available
> 
> mmm let me think a moment ... 🤔
> 
> 1. the easy solution is just to ignore the Rust again for the moment in this PR (and delay the problem)
> 2. if we want to do the proper thing, we need to find a good place on the Rust side; I'm thinking about adding yet another crate, random name suggestion: `ekoupling`, where we provide quasi the equivalent to the `eko.couplings` module: specifically, the beta functions and their solution. I'm worried about dependency management and how to disentangle stuff. Do you have an opinion? @tgiani may I ask for your opinion as well?

I would agree with what Giacomo said, so delay the problem for the time being and put an `ekoupling` implementation on the to do list

**Pull request merged**
