### PR TITLE
Use Poetry for RTD docs deps installation

### PR DESCRIPTION
**Pull request by AleCandido**

### CODE REVIEW

**Comment by AleCandido** [comment]
@felixhekhorn this should be ready as it is

**Comment by felixhekhorn** [comment]
let's wait for https://readthedocs.org/projects/eko/builds/20754504/

**Review by felixhekhorn — APPROVED** [review]
It worked https://eko.readthedocs.io/en/rtd-poetry/index.html - the moment we merge we can deactivate the branch on rtd again

**Comment by AleCandido** [comment]
Once in a while, I've been able to author a quick one ;)

**Pull request merged**
