### PR TITLE
Invert ekomark-ekobox dependency

### LINKED ISSUE #122: Cut `banana` out of `ekobox`
Maybe the solution is just a forth package, `ekobox` and `ekomark` will depend on it, but at least `ekobox` won't depend on `ekomark`, and we're sure will not depend on `banana`.

### PR DESCRIPTION
**Pull request by felixhekhorn**
Closes #122

### CODE REVIEW

**Review by AleCandido — APPROVED** [review]
Since #225 is already approved, please merge before that one

**Review by giacomomagni — COMMENTED** [review]
I'm fine with this. 
I imagine this will break the dependency in many tools right?

**Comment by AleCandido** [comment]
> I'm fine with this. I imagine this will break the dependency in many tools right?

Only those using `apply_pdf` directly, in principle (and outside our packages I'm not sure it is used that much).

**Review by andreab1997 — APPROVED** [review]

**Comment by andreab1997** [comment]
Fine for me, I don't see anything harmful. For sure I will need to update something as @giacomomagni was saying but nothing too complicate I believe.

**Pull request merged**
